# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 12 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Bzr
      - run: sudo apt install brz
      
      - name: Setup SSH tapaal-gui
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SECRET_PRIVATE_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Sync tapaal-gui
        run: |
          bzr branch lp:tapaal
          cd tapaal
          bzr push git@github.com:TAPAAL/tapaal-gui.git,branch=master --lossy

      - name: Sync tapaal-gui cpn
        run: |
          bzr branch lp:~tapaal-contributor/tapaal/cpn-gui-dev
          cd cpn-gui-dev
          bzr push git@github.com:TAPAAL/tapaal-gui.git,branch=cpn-gui-dev --lossy
      #- name: Setup SSH verifytapn
      #  run: |
      #    echo "${{ secrets.SECRET_PRIVATE_DEPLOY_KEY_VERIFYTAPN }}" > ~/.ssh/id_rsa
      #    chmod 600 ~/.ssh/id_rsa

      #- name: Sync verifytapn
      #  run: |
      #    bzr branch lp:verifytapn
      #    cd verifytapn 
      #    bzr push git@github.com:TAPAAL/verifytapn.git,branch=master --lossy
          
        
      #- name: Setup SSH verifypn
      #  run: |
      #    echo "${{ secrets.SECRET_PRIVATE_DEPLOY_KEY_VERIFYPN }}" > ~/.ssh/id_rsa
      #    chmod 600 ~/.ssh/id_rsa
          
      #- name: Sync verifypn
      #  run: | 
      #    bzr branch lp:verifypn
      #    cd verifypn
      #    bzr push git@github.com:TAPAAL/verifypn.git,branch=master --lossy
          
      
